### ISSUE TITLE
Xiaomi Mi Box (US version)

### ISSUE THREAD

**Issue by denysbutenko** [cachapa/AerialDream#3] opened 2016-12-17 18:37 UTC
It works nicely on Google Nexus Player but some time ago I bought Xiaomi Mi Box (US version) and it seems doesn't work correctly.

**Description:**
It looks good in the beginning but after a few minutes I getting a lot of errors at bottom of the screen and as result device ceases to be responsive. Sometimes it just stops.
Android: 6.0.1

**How to stop spam error notification:**
Open app settings and click "Stop service".

Can you check that? I'd like to help with fixing the issue but I'm not Android developer.

**Comment by cachapa** [comment] 2016-12-18 10:42
Unfortunately I don't have access to any Mi Box, so I can't figure out what the problem is.
It sounds a lot like a problem that's been reported on Sony TVs, but again, I have no access to the necessary hardware in order to debug it.

**Comment by denysbutenko** [comment] 2016-12-18 12:17
How can I help with debugging?

**Comment by cachapa** [comment] 2016-12-19 10:07
Typically, HW-specific problems like this are very hard to debug.
Unfortunately I don't think there's much you can help with unless you want to dive *really* deep into Android development.

**Comment by denysbutenko** [comment] 2016-12-19 11:20
Just noticed that when disabling "App notifications" it worked fine for the first day. 
Today it only shows "Loading aerial..."

**Comment by cachapa** [comment] 2017-02-21 19:24
I just published an update which changes how videos are handled.
It's a long shot, but could you test it again?

**Comment by cachapa** [comment] 2018-02-10 18:02
The problem seems to be the same as in issue #4. I'm closing this ticket since the other one has more information,

**Closed by cachapa** 2018-02-10 18:02 UTC
