### ISSUE TITLE
Add HDR option

### ISSUE THREAD

**Issue by kristofferR** [cachapa/AerialDream#29] opened 2020-10-08 23:31 UTC
I read [here](https://github.com/cachapa/AerialDream/issues/11#issuecomment-421400306) that HDR was disabled because it messes up fades.

I'd much rather have a few seconds of a janky/no fade and minutes/hours of beautiful HDR video than a few seconds of a nice fade and minutes/hours of mediocre SDR.

Please add an option to enable HDR videos for the ones who makes the same calculation as me.

**Comment by cachapa** [comment] 2020-10-09 06:41
The problem isn't that the fade transitions become "janky", but that it completely breaks the application.

I've already decided that the way forward is to remove the fades, but doing so will involve a lot of rewriting for which I currently don't have the time.

I'm closing this issue and following this in #30

**Closed by cachapa** 2020-10-09 06:41 UTC
