### ISSUE TITLE
2017 and 2018 Aerials stuck on Loading Aerial

### ISSUE THREAD

**Issue by josh-the-tech** [cachapa/AerialDream#21] opened 2019-05-09 13:24 UTC
On 1.6 and 1.7, most Aerials from the 2017 and 2018 collection will not load (1080 and 4K) and the app just says on "Loading Aerial...". I noticed this first on the Fire TV Stick (sideloaded) so decided to test on the Samsung Galaxy A40 I'm currently testing at work. The same issue occurs so it doesn't appear to be related to the Fire TV Stick.

**Comment by cachapa** [comment] 2019-05-10 07:01
Strange, I just tested all of them and they seem to be working fine.
Could it be a temporary network issue?

Dr. Daniel Cachapa

**Comment by josh-the-tech** [comment] 2019-05-10 07:03
Thanks for responding. Strangely it did this on 1.6 too. I’ll do some testing on another network and let you know. Is there any way to get logs that may point to the cause?
  

  
Thanks,
  
  
  
 Kind Regards,  

  
Josh Hancock
  
  
  
  

  
  
>

**Comment by cachapa** [comment] 2019-05-10 07:07
The video player does log some things to the debug console but it's not
accessible without having the android developer tools installed in your
computer.
Otherwise I can't think of anything. Because the app is intended to be used
as a screensaver, I never implemented anything in the way of exposing
errors. The idea was that if there was an error in one run, hopefully it'd
run fine the next time.

Dr. Daniel Cachapa

**Comment by josh-the-tech** [comment] 2019-05-10 07:12
No worries. I’ll get it on my laptop later and take a look. They won’t load whilst on my work WiFi (we don’t block anything) either so suggests there could be a network error maybe at their end. I do know when trying to make newer aerials work with the windows version of the screensaver, threw up some certificate errors on the sylvan.apple.com URLs.
  

  
Will take a look and see if I can pull out some info/logs.   
  
  
  
 Kind Regards,  

  
Josh Hancock
  
  
  
  

  
  
>

**Comment by cachapa** [comment] 2019-05-10 07:26
Now that you mention it, the apple domain is throwing certificate errors, I assume because they're using a self-signed one.
Aerial Dream should be ignoring it though. I'll have to check that.

**Comment by josh-the-tech** [comment] 2019-05-11 20:25
I see that the code to get the json files ignore certificate errors. Is there code to do the same thing for the actual URLs inside the JSON? Those URLs point to https:// so will throw them. The other option is to provide the Apple self signed cert as part of the package (if that’s even possible and/or allowed)

**Comment by cachapa** [comment] 2019-05-13 07:19
The video player is currently not configured to explicitly ignore the certificate. I'll check for a way to do that.
Bundling the certificate would be another option but honestly that just seems like overkill.

**Comment by josh-the-tech** [comment] 2019-05-13 10:00
Hopefully ignoring the certificate will be easy enough to do. If you need the root certificate (as this is what I had to do to make it work on the Windows version of the screensaver), you can get this from a Mac quite easily. If you don’t have a Mac to access, let me know and I can get it for you.   
  
  
  
 Kind Regards,  

  
Josh Hancock
  
  
  
  

  
  
>

**Comment by meepmeep** [comment] 2019-05-13 12:14
Hi

I have the same issue on my Sony Android TV. A lot of Aerials don't load. And, due to the system configuration, I don't have access to log (and certainly can't add a new root certificate).
Is there another way to debug that ?

**Comment by therealhoodboy** [comment] 2019-05-14 17:14
Maybe you can look [here](https://github.com/JohnCoates/Aerial). I've installed this screensaver and all aerials are loading instantly.

**Comment by josh-the-tech** [comment] 2019-05-14 20:12
Yep these would as that screensaver is for Mac. A Mac has the Apple root certificate the sylvan website uses. I had to use a Mac to get hold of this for the Windows variant to make the 2017 json file work with it so there won’t be anything in the Mac screensaver that would help unfortunately.   
  
  
  
 Kind Regards,  

  
Josh Hancock
  
  
  
  

  
  
>

**Comment by joshobrien91** [comment] 2019-05-15 02:58
Same here, on Sony Android TV, it will work, then other times it’ll get stuck on Loading Aerial, crashing/freezing also an issue which occurs regularly. 

Apple Phobos doesn’t have any issues, however no option to display location or time - https://play.google.com/store/apps/details?id=ru.gelin.android.phobosapple&hl=en_US

**Comment by gentlecat** [comment] 2019-05-18 21:40
Having similar issues on my Sony TV. I see these exceptions in Logcat, which might be related:

```
2019-05-18 14:37:42.847 24447-29334/? W/MediaCodecRenderer: Failed to initialize decoder: OMX.MTK.VIDEO.DECODER.HEVC
    android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1935)
        at android.media.MediaCodec.configure(MediaCodec.java:1864)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:570)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:775)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:511)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1174)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:635)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:729)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:643)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-05-18 14:37:42.848 24447-29334/? E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.HEVC, Format(1, null, null, video/hevc, null, -1, null, [3840, 2160, 29.97003], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:513)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1174)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:635)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:729)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:643)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.HEVC, Format(1, null, null, video/hevc, null, -1, null, [3840, 2160, 29.97003], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:782)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:511)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1174) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:635) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:729) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:643) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1935)
        at android.media.MediaCodec.configure(MediaCodec.java:1864)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:570)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:843)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:775)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:511) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1174) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:635) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:729) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:643) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

**Comment by cachapa** [comment] 2019-05-19 06:55
It seems your Sony TV doesn't support the video codec Apple is using for some of their videos.
I have similar issues when I tried playing the HDR versions, which is why I left them out of the app for now.

**Comment by hackel** [comment] 2019-07-22 20:23
I'm seeing this behaviour on my HiSense TV also.  No 4K videos will play at all, it just stays stuck on "Loading Aerial..."  If I switch 2017 and/or 2018 to 1080, they only seem to play half the time.  Will try to get ADB enabled to hopefully get some more information about what is failing.

**Comment by josh-the-tech** [comment] 2019-11-03 11:32
Decided to look into this a bit further now I understand ADB logging better than I did a few months ago. I've gotten logs and it appears the issue I'm getting is the HEVC decoder having a fatal error. This applies to the 2017 and 2018 videos on 1080 and 4K. I have the Fire TV Stick 2nd Gen. Could it be that I need the 4K version of the Fire TV Stick to make these work?

**Comment by DJay-X** [comment] 2019-11-07 15:38
Same here with ZTE Spro 2 Projector Android 4.4  seeing a lot of the time just "Loading Aerial".

I love this screensaver and hope development will go on and have an update soon. 

Thanks in advance for your work @cachapa

**Comment by cachapa** [comment] 2019-11-08 10:39
It's hard to debug decoder issues since that part is delegated to the video library we're using (exoplayer), which itself delegates to the system decoder.

I can try updating the library to the latest release and see if that helps, but these things are very strongly dependent on the hardware, i.e. how popular and how powerful it is.

In the specific case of Amazon devices, they're running a fork of Android which has (or used to have) known incompatibilities in the media space, so it's hard to say if they'll ever work properly.

**Comment by sheeput** [comment] 2019-12-13 17:59
I'm not sure if it is appropriate to comment here after it is closed (let me know). I'm seeing the same issue. I've noticed that this seems to happen when my phone is locked and then the screensaver is initiated.   It works fine if I unlock my phone and then it comes on.  Is it some kind of security/permission thing?

**Comment by hackel** [comment] 2020-06-25 02:57
I was just playing with Aerial again, experiencing the same issues, but as I continued playing around to capture a logcat, a 4K video actually played!  I had everything disabled except for 2017 4K.  I'm still seeing a lot of errors like `Failed to initialize decoder: OMX.MTK.VIDEO.DECODER.HEVC`.  I captured the following logcat if it's useful at all: https://hastebin.com/uhezatarad  As far as I can tell, the logcat output is identical when it plays as when it doesn't.

Of course, I have no way to know for sure that this was actually a 4K video, that's just what it is set to.  It seems to play roughly 33% of the time now.  The videos do seem to be stuttering just a bit.  It's not exactly a high-powered device, but it plays 4K video in Netflix just fine, so probably more codec issues.

It would be great if Aerial could detect the failure and just try again.

This is on a Hisense running Android TV 8.0.

**Comment by cachapa** [comment] 2020-06-25 09:16
I've just published a new version to beta with the latest video player library. It might help with the decoder issues, but I'm starting to think that Apple is using a video encoding which has issues in some Android devices.

Could you try the latest beta and see if it helps any? Otherwise I'm afraid the only option is to disable any recent playlists, which use those new codecs.

**Comment by labba** [comment] 2020-06-29 23:37
how can i get the beta APK to download ?

**Comment by cachapa** [comment] 2020-06-30 06:45
I thought the option to join the beta would be visible in the play store. Otherwise you can join here:
https://play.google.com/apps/testing/com.codingbuffalo.aerialdream

**Comment by labba** [comment] 2020-06-30 07:11
thanks,

for me i have TCL C8 with android TV OS version 9 and it hangs on "Loading Aerial..." like before

is there anything i can give or log file it generate i can give you  ?

**Comment by cachapa** [comment] 2020-06-30 07:24
No need, the problem is already known and not something that can be easily fixed.
I keep this issue open to track it but honestly the fix would require an extensive rewrite to allow only one video to play at a time, which I currently cannot do.

**Comment by labba** [comment] 2020-06-30 08:53
i also see the same issue on Android TV emulation of Android studio. doesn't it help to pinpoint the issue ?

**Comment by labba** [comment] 2020-07-02 08:22
btw,
i have seen this issue in the past solved by allowing the application to load a different player during application loading and once the used allow it  the appliaction is using it by default
the player i have seen that worked will in that issue was MX Player and it solve the issue.

**Comment by cachapa** [comment] 2020-07-02 17:39
Unfortunately the Android TV emulator doesn't seem to be running on my computer, so I can't test right now.

I don't know what you mean by "load a different player".

**Comment by cachapa** [comment] 2020-10-09 06:42
I'm closing this issue and following this in #30

**Closed by cachapa** 2020-10-09 06:42 UTC
