### ISSUE TITLE
[Request] Use full screen in Essential phone PH-1

### ISSUE THREAD

**Issue by hidai** [cachapa/AerialDream#12] opened 2018-01-17 07:42 UTC
I like AerialDream. However, it doesn't cover full screen of my Essential Phone. The status bar at the top and the bottom area for three system buttons are not filled with movies.

I think this article is related to this issue.
https://www.xda-developers.com/essential-phone-no-longer-whitelist-for-fullscreen-apps/

**Comment by cachapa** [comment] 2018-01-17 08:04
It seems the problem is that the app doesn't specify a max aspect ratio. According to these [docs](https://developer.android.com/guide/practices/screens_support.html#MaxAspectRatio) it should be enough to recompile the app targeting the latest API.

I'll try to create an update as soon as possible.

**Comment by cachapa** [comment] 2018-02-10 17:01
Update was finally pushed, so the issue should be fixed.

**Comment by hidai** [comment] 2018-02-15 08:24
Thanks cachapa, I updated the app to the latest (Feb 8, 2018) version.
But it doesn't cover full screen of my Essential Phone. I re-installed the app, but it didn't help.
Hmm...

**Comment by cachapa** [comment] 2018-02-15 10:24
Strange. I'll reopen the ticket and see if I can find a way to test it.

**Comment by cachapa** [comment] 2018-09-14 15:39
Should be fixed in the latest release

**Closed by cachapa** 2018-09-14 15:39 UTC
