### ISSUE TITLE
[Request] Allow installation to external SD

### ISSUE THREAD

**Issue by uratrtl** [cachapa/AerialDream#9] opened 2017-05-26 03:41 UTC
I have an android tv and it has a very small amount of storage, if I could copy this app and its cache to my mounted external storage my space issues would be resolved.

*RESOLVED* once I enabled developer mode on my shield tv I was able to force instal ArialDream onto my mounted external storage, I set it to cache all and its already up to 7.5 gigs from yesterday basically the entire internal storage of my 2017 shield.

**Comment by cachapa** [comment] 2017-10-30 17:17
I changed the title back since the problem isn't as much "resolved" as it was "resolved-for-me" :-)
But good to know that forcing the installation in the external storage fixes the problem. I'll try enabling that option in the manifest and see if it works.

Unfortunately I can't test it myself (I don't have external storage connected to my devices), so I'll have to depend on someone to test it.

**Comment by cachapa** [comment] 2018-02-10 17:04
Update with the new manifest has been published. I don't know if this fixes the issue (I can't test it easily) but I'm going to be optimistic and close this ticket anyway.

**Closed by cachapa** 2018-02-10 17:04 UTC
