### ISSUE TITLE
"Loading Aerial..." when set to 4K on Sony TV

### ISSUE THREAD

**Issue by jbl0ggs** [cachapa/AerialDream#28] opened 2020-09-11 04:41 UTC
Sony TV Bravia 4K X850G
Android Ver: 9
Sec. Patch April 1, 2020
Kernel: 4.9.125

It seems to be working fine when all years 2015-2019 are set to HD

When I Disable 2015 and set 2016-2019 to 4K then it only displays "Loading Aerial..."

If I enable 2015 and keep the rest to 4K, it looks like the 2015 images display but when it comes across the 4K, it just hangs on the 2015 image.

**Comment by menaren** [comment] 2020-09-13 16:04
Hi, 
This is likely a duplicate of #21 and #27. You can find [here ](https://github.com/cachapa/AerialDream/issues/27#issuecomment-671087490) the answer of @cachapa saying that the app may crash when the hardware is not powerful enough to handle 4K videos (especially during transitions).

Your issue is well known and maybe require a lot of work to be fixed. A workaround (if I can say so) I would suggest is to select only 1080p sources, you'll achieve your goal of looking like an Apple TV.

**Comment by cachapa** [comment] 2020-10-09 06:42
I'm closing this issue and following this in #30

**Closed by cachapa** 2020-10-09 06:42 UTC
